In [1]:
import pandas as pd
import numpy as np

1. Import Data

In [2]:
listings_data = pd.read_csv('../Data/listings.csv')
reviews_data = pd.read_csv('../Data/reviews.csv')
neighborhoods_data = pd.read_csv('../Data/neighbourhoods.csv')

In [3]:
listings_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 25449 entries, 0 to 25448
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              25449 non-null  int64
 1   name                            25449 non-null  str
 2   host_id                         25449 non-null  int64
 3   host_name                       25447 non-null  str
 4   neighbourhood_group             25449 non-null  str
 5   neighbourhood                   25449 non-null  str
 6   latitude                        25449 non-null  float64
 7   longitude                       25449 non-null  float64
 8   room_type                       25449 non-null  str
 9   price                           21870 non-null  float64
 10  minimum_nights                  25449 non-null  int64
 11  number_of_reviews               25449 non-null  int64
 12  last_review                     22255 non-null  str
 13  reviews_per_month               22255 non-null  float64
 14  calculated_host_listings_count  25449 non-null  int64
 15  availability_365                25449 non-null  int64
 16  number_of_reviews_ltm           25449 non-null  int64
 17  license                         24290 non-null  str
dtypes: float64(4), int64(7), str(7)
memory usage: 3.5 MB

In [12]:
listings_data.shape, reviews_data.shape, neighborhoods_data.shape

((25449, 18), (1814844, 2), (134, 2))

In [5]:
listings_data.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                            2
neighbourhood_group                  0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                             3579
minimum_nights                       0
number_of_reviews                    0
last_review                       3194
reviews_per_month                 3194
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                           1159
dtype: int64

In [9]:
listings_data.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
count,2.544900e+04,2.544900e+04,25449.000000,25449.000000,21870.000000,25449.000000,25449.000000,22255.000000,25449.000000,25449.000000,25449.000000
mean,6.052322e+17,2.287182e+08,38.762926,-9.207847,248.116049,4.719989,69.289206,1.566873,25.998075,217.148061,13.638257
std,5.914290e+17,2.214487e+08,0.114548,0.112146,1812.958718,16.810821,110.598085,1.551474,64.004266,129.336846,18.592469
min,6.499000e+03,1.445500e+04,38.675790,-9.486970,9.000000,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000
25%,2.635673e+07,2.868791e+07,38.711030,-9.287910,75.000000,1.000000,3.000000,0.390000,1.000000,90.000000,0.000000
50%,6.598273e+17,1.462857e+08,38.719520,-9.147947,110.000000,2.000000,21.000000,1.090000,5.000000,263.000000,5.000000
75%,1.182779e+18,4.389003e+08,38.746920,-9.135128,167.000000,3.000000,86.000000,2.320000,16.000000,332.000000,21.000000
max,1.513766e+18,7.196566e+08,39.304030,-8.862100,86733.000000,1000.000000,1787.000000,29.720000,391.000000,365.000000,329.000000

In [10]:
listings_data.describe(include='O')

/tmp/ipykernel_166989/2282621208.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  listings_data.describe(include='O')

,name,host_name,neighbourhood_group,neighbourhood,room_type,last_review,license
count,25449,25447,25449,25449,25449,22255,24290
unique,24514,3804,16,129,4,1661,13613
top,Excelente Quarto Central,Pedro,Lisboa,Santa Maria Maior,Entire home/apt,2025-09-07,Exempt
freq,47,647,17428,3482,18824,760,4882